### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by thedrow** [jordansissel/pleaserun#112]
Can we run tests in CI please?

**Comment by jordansissel** [comment]
I'd love to, but I haven't explored any CI that would work well for pleaserun (It usually requires root and a functioning service platform, such as systemd, running). For now, I run the suite manually in VMs on platforms I have easy access to.

**Comment by thedrow** [comment]
You can use Travis or CircleCI or anything else that supports running Docker instances.

**Comment by jordansissel** [comment]
Pleaserun doesn't do well in docker because the integration tests need
systemd, upstart, etc. I gave up maintaining images for that a long time
ago because doing this in docker was very difficult (at the time).

I welcome patches that help with this, but as I don't use docker (I use
vms) I don't have energy to do it.

**Comment by jordansissel** [comment]
Closing as idle w/o solution. I'd love to use Travis, but most of pleaserun's test suite can't run in docker anyway (missing systemd, upstart, etc).
