### ISSUE TITLE
No build/test instructions

### ISSUE THREAD

**Issue by exowaucka** [jordansissel/pleaserun#117]
I'm trying to make a change to pleaserun, and I think I've built it, but I can't seem to figure out how to test it or run the current version.  Some instructions in the README or a separate file would be helpful.

**Comment by jordansissel** [comment]
Until someone writes some nice dev docs, here's what to do:

* Install dependencies: `bundle install` -- this requires bundler, which can be installed with `gem install bundler`. I *highly* recommend *not* using your system/distro's ruby as it is either ancient or patched in strange ways.
* Build: nothing. 
* Test: `bundle exec rspec`

Lots of tests are skipped by default because they are integration tests that require being run on platforms pleaserun targets for support.
