### ISSUE TITLE
Defaults to trying to install scripts on macos x

### ISSUE THREAD

**Issue by vjanelle** [jordansissel/pleaserun#135]
https://twitter.com/jordansissel/status/1018973793283293184

```
pleaserun the_thing
```
```
No platform selected. Autodetecting... {:platform=>"launchd", :version=>"5.3.0", :level=>:warn}
No name given, setting reasonable default based on the executable {:name=>"the_thing", :level=>:warn}
Writing file {:destination=>"/Library/LaunchDaemons/the_thing.plist"}
Access denied in writing a file. Maybe we need to be root? {:path=>"/Library/LaunchDaemons/the_thing.plist", :level=>:error}
An error occurred: Errors occurred while writing files {:level=>:error}
```

attempted to do the same when passed in --platform for systemd, etc.

**Comment by jordansissel** [comment]
Hmm.

https://github.com/jordansissel/pleaserun/blob/7621b9889b79025364ee52fb7b58f4abf2dc7b75/lib/pleaserun/cli.rb#L24

The --install flag has no default, which should mean it defaults to `nil` (aka false). I wonder if something changed upstream in Clamp? I'll do some digging.

**Comment by jordansissel** [comment]
🤦‍♂️  my hypothesis was way off.

I believe this may have been introduced by 9f4d073e. I haven't fully tested, but my hypothesis is:

* An older commit (cba0c1df) created the `--install-prefix` flag and gave it a default of `/`
* 9f4d073e made it use the `--install-prefix` setting, if present, or fall back to the previous temporary directory behavior
* Because `--install-prefix` has a default value, `pleaserun` now seems to always install to `/` instead of a random temporary directory as it did before.

I'll think of a way to resolve this. For now, you can specify your own `--install-prefix` path as a workaround.

**Comment by vjanelle** [comment]
That's what I ended up doing.  Worked out for me since I was delivering the scripts via puppet in any event.
