### ISSUE TITLE
sysv lsb3.1 nice placeholder in default when not honoured in script

### ISSUE THREAD

**Issue by jstangroome** [jordansissel/pleaserun#91]
The generated `default` file for sysv lsb3.1 contains a `nice=""` placeholder suggesting that a value could be specified in the deployed `default` file and it would be honoured by the init script.

However, when the `nice` attribute is unspecified at template render time, the init script excludes the lines that would otherwise process the `nice` environment variable.

Ideally the init script would always include lines to honour the `nice` environment variable if the variable has a value.

This problem is visible in the Debian package for https://github.com/elastic/logstash-forwarder 0.4.0

**Comment by jordansissel** [comment]
I'm on the fence about how to solve this.

Some background - My intention with pleaserun is that it is used to generate a script you only modify by re-running pleaserun; this means I didn't want any user-serviceable parts to be expected from the generated code.

With this in mind, the way for you to solve this problem (with the above context) is to run pleaserun yourself and set the nice level through pleaserun.

Given the above, I think the bug is that `nice=""` is present in the `default` file when it is not specified.

Long term, my intention is to remove the `default` file.

**Comment by jordansissel** [comment]
I'm open to discussion on this, though.

**Comment by jstangroome** [comment]
I figured removing `nice=""` from the `default` file would be the likely result, hence my use of "ideally" in my original post. :)

For the scenario of an end-user executing `pleaserun` your preferred solution makes perfect sense.

For the scenario of `pleaserun` being used to generate the scripts to include in `logstash-forwarder`'s official Debian package (or so it seems) then I'd prefer my "ideal" solution. But maybe this scenario should be handled in the `logstash-forwarder` code base.

**Comment by b-long** [comment]
:+1:

**Comment by jordansissel** [comment]
I will remove the 'nice' value from the defaults file on the sysv platform. <3

**Comment by jordansissel** [comment]
Actually, I try to now set it to a default value of 0 if there is no value for $nice.

**Comment by jordansissel** [comment]
Hopefully this helps!
